// import { Geist, Geist_Mono } from "next/font/google"; //Overvej at bruge dine egne fonte her
import { Poppins } from "next/font/google";
import "./globals.css"; //Muligheden for at bruge et traditionelt CSS stylesheet
import HeaderComponent from "@/components/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: /* "Create Next App" */ "iWatch", //Titel på fanen (Ligesom title tag i HTML)
  description: /* "Generated by create next app" */ "",


  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.variable} antialiased bg-gradient-to-b from-[#B6CCDA] to-[#C8DCE6] 
        h-screen w-screen
        px-18 flex flex-col`}
      >
        <HeaderComponent />

        {children /* Ligesom slot i Astro */}
      </body>
    </html>
  );
}
